defaults: &defaults

development:

test:

production:
  app_id: "<%= ENV['FOURSQUARE_CLIENT_ID'] %>"
  app_secret: "<%= ENV['FOURSQUARE_CLIENT_SECRET'] %>"
  callback_url: "<%= ENV['OAUTH_CALLBACK'] %>"
  aws_key: "<%= ENV['AWS_KEY'] %>"
  aws_secret: "<%= ENV['AWS_SECRET'] %>"
  cloudwatch_key: "<%= ENV['CLOUDWATCH_KEY'] %>"
  cloudwatch_secret: "<%= ENV['CLOUDWATCH_SECRET'] %>"
  google_maps_key: "<%= ENV['GOOGLE_MAPS_KEY'] %>"
  s3_bucket: "<%= ENV['AWS_S3_BUCKET'] %>"
